// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef PROTOBUF_rpc_2eproto__INCLUDED
#define PROTOBUF_rpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace thefox {
namespace rpc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rpc_2eproto();
void protobuf_AssignDesc_rpc_2eproto();
void protobuf_ShutdownFile_rpc_2eproto();

class Call;
class Reply;
class NonRpcMsg;
class Box;
class Placeholder;
class HeartBeath;

// ===================================================================

class Call : public ::google::protobuf::Message {
 public:
  Call();
  virtual ~Call();

  Call(const Call& from);

  inline Call& operator=(const Call& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Call& default_instance();

  void Swap(Call* other);

  // implements Message ----------------------------------------------

  Call* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Call& from);
  void MergeFrom(const Call& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // required string service = 2;
  inline bool has_service() const;
  inline void clear_service();
  static const int kServiceFieldNumber = 2;
  inline const ::std::string& service() const;
  inline void set_service(const ::std::string& value);
  inline void set_service(const char* value);
  inline void set_service(const char* value, size_t size);
  inline ::std::string* mutable_service();
  inline ::std::string* release_service();
  inline void set_allocated_service(::std::string* service);

  // required string method = 3;
  inline bool has_method() const;
  inline void clear_method();
  static const int kMethodFieldNumber = 3;
  inline const ::std::string& method() const;
  inline void set_method(const ::std::string& value);
  inline void set_method(const char* value);
  inline void set_method(const char* value, size_t size);
  inline ::std::string* mutable_method();
  inline ::std::string* release_method();
  inline void set_allocated_method(::std::string* method);

  // optional bytes request = 4;
  inline bool has_request() const;
  inline void clear_request();
  static const int kRequestFieldNumber = 4;
  inline const ::std::string& request() const;
  inline void set_request(const ::std::string& value);
  inline void set_request(const char* value);
  inline void set_request(const void* value, size_t size);
  inline ::std::string* mutable_request();
  inline ::std::string* release_request();
  inline void set_allocated_request(::std::string* request);

  // @@protoc_insertion_point(class_scope:thefox.rpc.Call)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_service();
  inline void clear_has_service();
  inline void set_has_method();
  inline void clear_has_method();
  inline void set_has_request();
  inline void clear_has_request();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 id_;
  ::std::string* service_;
  ::std::string* method_;
  ::std::string* request_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static Call* default_instance_;
};
// -------------------------------------------------------------------

class Reply : public ::google::protobuf::Message {
 public:
  Reply();
  virtual ~Reply();

  Reply(const Reply& from);

  inline Reply& operator=(const Reply& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Reply& default_instance();

  void Swap(Reply* other);

  // implements Message ----------------------------------------------

  Reply* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Reply& from);
  void MergeFrom(const Reply& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // required bool result = 2;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 2;
  inline bool result() const;
  inline void set_result(bool value);

  // optional bytes response = 3;
  inline bool has_response() const;
  inline void clear_response();
  static const int kResponseFieldNumber = 3;
  inline const ::std::string& response() const;
  inline void set_response(const ::std::string& value);
  inline void set_response(const char* value);
  inline void set_response(const void* value, size_t size);
  inline ::std::string* mutable_response();
  inline ::std::string* release_response();
  inline void set_allocated_response(::std::string* response);

  // @@protoc_insertion_point(class_scope:thefox.rpc.Reply)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_response();
  inline void clear_has_response();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 id_;
  ::std::string* response_;
  bool result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static Reply* default_instance_;
};
// -------------------------------------------------------------------

class NonRpcMsg : public ::google::protobuf::Message {
 public:
  NonRpcMsg();
  virtual ~NonRpcMsg();

  NonRpcMsg(const NonRpcMsg& from);

  inline NonRpcMsg& operator=(const NonRpcMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NonRpcMsg& default_instance();

  void Swap(NonRpcMsg* other);

  // implements Message ----------------------------------------------

  NonRpcMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NonRpcMsg& from);
  void MergeFrom(const NonRpcMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string msg_type = 1;
  inline bool has_msg_type() const;
  inline void clear_msg_type();
  static const int kMsgTypeFieldNumber = 1;
  inline const ::std::string& msg_type() const;
  inline void set_msg_type(const ::std::string& value);
  inline void set_msg_type(const char* value);
  inline void set_msg_type(const char* value, size_t size);
  inline ::std::string* mutable_msg_type();
  inline ::std::string* release_msg_type();
  inline void set_allocated_msg_type(::std::string* msg_type);

  // required bytes msg_body = 2;
  inline bool has_msg_body() const;
  inline void clear_msg_body();
  static const int kMsgBodyFieldNumber = 2;
  inline const ::std::string& msg_body() const;
  inline void set_msg_body(const ::std::string& value);
  inline void set_msg_body(const char* value);
  inline void set_msg_body(const void* value, size_t size);
  inline ::std::string* mutable_msg_body();
  inline ::std::string* release_msg_body();
  inline void set_allocated_msg_body(::std::string* msg_body);

  // @@protoc_insertion_point(class_scope:thefox.rpc.NonRpcMsg)
 private:
  inline void set_has_msg_type();
  inline void clear_has_msg_type();
  inline void set_has_msg_body();
  inline void clear_has_msg_body();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* msg_type_;
  ::std::string* msg_body_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static NonRpcMsg* default_instance_;
};
// -------------------------------------------------------------------

class Box : public ::google::protobuf::Message {
 public:
  Box();
  virtual ~Box();

  Box(const Box& from);

  inline Box& operator=(const Box& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Box& default_instance();

  void Swap(Box* other);

  // implements Message ----------------------------------------------

  Box* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Box& from);
  void MergeFrom(const Box& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .thefox.rpc.Call call = 1;
  inline bool has_call() const;
  inline void clear_call();
  static const int kCallFieldNumber = 1;
  inline const ::thefox::rpc::Call& call() const;
  inline ::thefox::rpc::Call* mutable_call();
  inline ::thefox::rpc::Call* release_call();
  inline void set_allocated_call(::thefox::rpc::Call* call);

  // optional .thefox.rpc.Reply reply = 2;
  inline bool has_reply() const;
  inline void clear_reply();
  static const int kReplyFieldNumber = 2;
  inline const ::thefox::rpc::Reply& reply() const;
  inline ::thefox::rpc::Reply* mutable_reply();
  inline ::thefox::rpc::Reply* release_reply();
  inline void set_allocated_reply(::thefox::rpc::Reply* reply);

  // optional .thefox.rpc.NonRpcMsg nonrpc_msg = 3;
  inline bool has_nonrpc_msg() const;
  inline void clear_nonrpc_msg();
  static const int kNonrpcMsgFieldNumber = 3;
  inline const ::thefox::rpc::NonRpcMsg& nonrpc_msg() const;
  inline ::thefox::rpc::NonRpcMsg* mutable_nonrpc_msg();
  inline ::thefox::rpc::NonRpcMsg* release_nonrpc_msg();
  inline void set_allocated_nonrpc_msg(::thefox::rpc::NonRpcMsg* nonrpc_msg);

  // @@protoc_insertion_point(class_scope:thefox.rpc.Box)
 private:
  inline void set_has_call();
  inline void clear_has_call();
  inline void set_has_reply();
  inline void clear_has_reply();
  inline void set_has_nonrpc_msg();
  inline void clear_has_nonrpc_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::thefox::rpc::Call* call_;
  ::thefox::rpc::Reply* reply_;
  ::thefox::rpc::NonRpcMsg* nonrpc_msg_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static Box* default_instance_;
};
// -------------------------------------------------------------------

class Placeholder : public ::google::protobuf::Message {
 public:
  Placeholder();
  virtual ~Placeholder();

  Placeholder(const Placeholder& from);

  inline Placeholder& operator=(const Placeholder& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Placeholder& default_instance();

  void Swap(Placeholder* other);

  // implements Message ----------------------------------------------

  Placeholder* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Placeholder& from);
  void MergeFrom(const Placeholder& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:thefox.rpc.Placeholder)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static Placeholder* default_instance_;
};
// -------------------------------------------------------------------

class HeartBeath : public ::google::protobuf::Message {
 public:
  HeartBeath();
  virtual ~HeartBeath();

  HeartBeath(const HeartBeath& from);

  inline HeartBeath& operator=(const HeartBeath& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartBeath& default_instance();

  void Swap(HeartBeath* other);

  // implements Message ----------------------------------------------

  HeartBeath* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartBeath& from);
  void MergeFrom(const HeartBeath& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:thefox.rpc.HeartBeath)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_rpc_2eproto();
  friend void protobuf_AssignDesc_rpc_2eproto();
  friend void protobuf_ShutdownFile_rpc_2eproto();

  void InitAsDefaultInstance();
  static HeartBeath* default_instance_;
};
// ===================================================================


// ===================================================================

// Call

// required int64 id = 1;
inline bool Call::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Call::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Call::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Call::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 Call::id() const {
  return id_;
}
inline void Call::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// required string service = 2;
inline bool Call::has_service() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Call::set_has_service() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Call::clear_has_service() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Call::clear_service() {
  if (service_ != &::google::protobuf::internal::kEmptyString) {
    service_->clear();
  }
  clear_has_service();
}
inline const ::std::string& Call::service() const {
  return *service_;
}
inline void Call::set_service(const ::std::string& value) {
  set_has_service();
  if (service_ == &::google::protobuf::internal::kEmptyString) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void Call::set_service(const char* value) {
  set_has_service();
  if (service_ == &::google::protobuf::internal::kEmptyString) {
    service_ = new ::std::string;
  }
  service_->assign(value);
}
inline void Call::set_service(const char* value, size_t size) {
  set_has_service();
  if (service_ == &::google::protobuf::internal::kEmptyString) {
    service_ = new ::std::string;
  }
  service_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Call::mutable_service() {
  set_has_service();
  if (service_ == &::google::protobuf::internal::kEmptyString) {
    service_ = new ::std::string;
  }
  return service_;
}
inline ::std::string* Call::release_service() {
  clear_has_service();
  if (service_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = service_;
    service_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Call::set_allocated_service(::std::string* service) {
  if (service_ != &::google::protobuf::internal::kEmptyString) {
    delete service_;
  }
  if (service) {
    set_has_service();
    service_ = service;
  } else {
    clear_has_service();
    service_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string method = 3;
inline bool Call::has_method() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Call::set_has_method() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Call::clear_has_method() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Call::clear_method() {
  if (method_ != &::google::protobuf::internal::kEmptyString) {
    method_->clear();
  }
  clear_has_method();
}
inline const ::std::string& Call::method() const {
  return *method_;
}
inline void Call::set_method(const ::std::string& value) {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  method_->assign(value);
}
inline void Call::set_method(const char* value) {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  method_->assign(value);
}
inline void Call::set_method(const char* value, size_t size) {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  method_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Call::mutable_method() {
  set_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    method_ = new ::std::string;
  }
  return method_;
}
inline ::std::string* Call::release_method() {
  clear_has_method();
  if (method_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = method_;
    method_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Call::set_allocated_method(::std::string* method) {
  if (method_ != &::google::protobuf::internal::kEmptyString) {
    delete method_;
  }
  if (method) {
    set_has_method();
    method_ = method;
  } else {
    clear_has_method();
    method_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes request = 4;
inline bool Call::has_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Call::set_has_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Call::clear_has_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Call::clear_request() {
  if (request_ != &::google::protobuf::internal::kEmptyString) {
    request_->clear();
  }
  clear_has_request();
}
inline const ::std::string& Call::request() const {
  return *request_;
}
inline void Call::set_request(const ::std::string& value) {
  set_has_request();
  if (request_ == &::google::protobuf::internal::kEmptyString) {
    request_ = new ::std::string;
  }
  request_->assign(value);
}
inline void Call::set_request(const char* value) {
  set_has_request();
  if (request_ == &::google::protobuf::internal::kEmptyString) {
    request_ = new ::std::string;
  }
  request_->assign(value);
}
inline void Call::set_request(const void* value, size_t size) {
  set_has_request();
  if (request_ == &::google::protobuf::internal::kEmptyString) {
    request_ = new ::std::string;
  }
  request_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Call::mutable_request() {
  set_has_request();
  if (request_ == &::google::protobuf::internal::kEmptyString) {
    request_ = new ::std::string;
  }
  return request_;
}
inline ::std::string* Call::release_request() {
  clear_has_request();
  if (request_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = request_;
    request_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Call::set_allocated_request(::std::string* request) {
  if (request_ != &::google::protobuf::internal::kEmptyString) {
    delete request_;
  }
  if (request) {
    set_has_request();
    request_ = request;
  } else {
    clear_has_request();
    request_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Reply

// required int64 id = 1;
inline bool Reply::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Reply::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Reply::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Reply::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 Reply::id() const {
  return id_;
}
inline void Reply::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// required bool result = 2;
inline bool Reply::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Reply::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Reply::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Reply::clear_result() {
  result_ = false;
  clear_has_result();
}
inline bool Reply::result() const {
  return result_;
}
inline void Reply::set_result(bool value) {
  set_has_result();
  result_ = value;
}

// optional bytes response = 3;
inline bool Reply::has_response() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Reply::set_has_response() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Reply::clear_has_response() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Reply::clear_response() {
  if (response_ != &::google::protobuf::internal::kEmptyString) {
    response_->clear();
  }
  clear_has_response();
}
inline const ::std::string& Reply::response() const {
  return *response_;
}
inline void Reply::set_response(const ::std::string& value) {
  set_has_response();
  if (response_ == &::google::protobuf::internal::kEmptyString) {
    response_ = new ::std::string;
  }
  response_->assign(value);
}
inline void Reply::set_response(const char* value) {
  set_has_response();
  if (response_ == &::google::protobuf::internal::kEmptyString) {
    response_ = new ::std::string;
  }
  response_->assign(value);
}
inline void Reply::set_response(const void* value, size_t size) {
  set_has_response();
  if (response_ == &::google::protobuf::internal::kEmptyString) {
    response_ = new ::std::string;
  }
  response_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Reply::mutable_response() {
  set_has_response();
  if (response_ == &::google::protobuf::internal::kEmptyString) {
    response_ = new ::std::string;
  }
  return response_;
}
inline ::std::string* Reply::release_response() {
  clear_has_response();
  if (response_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = response_;
    response_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Reply::set_allocated_response(::std::string* response) {
  if (response_ != &::google::protobuf::internal::kEmptyString) {
    delete response_;
  }
  if (response) {
    set_has_response();
    response_ = response;
  } else {
    clear_has_response();
    response_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// NonRpcMsg

// required string msg_type = 1;
inline bool NonRpcMsg::has_msg_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NonRpcMsg::set_has_msg_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NonRpcMsg::clear_has_msg_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NonRpcMsg::clear_msg_type() {
  if (msg_type_ != &::google::protobuf::internal::kEmptyString) {
    msg_type_->clear();
  }
  clear_has_msg_type();
}
inline const ::std::string& NonRpcMsg::msg_type() const {
  return *msg_type_;
}
inline void NonRpcMsg::set_msg_type(const ::std::string& value) {
  set_has_msg_type();
  if (msg_type_ == &::google::protobuf::internal::kEmptyString) {
    msg_type_ = new ::std::string;
  }
  msg_type_->assign(value);
}
inline void NonRpcMsg::set_msg_type(const char* value) {
  set_has_msg_type();
  if (msg_type_ == &::google::protobuf::internal::kEmptyString) {
    msg_type_ = new ::std::string;
  }
  msg_type_->assign(value);
}
inline void NonRpcMsg::set_msg_type(const char* value, size_t size) {
  set_has_msg_type();
  if (msg_type_ == &::google::protobuf::internal::kEmptyString) {
    msg_type_ = new ::std::string;
  }
  msg_type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NonRpcMsg::mutable_msg_type() {
  set_has_msg_type();
  if (msg_type_ == &::google::protobuf::internal::kEmptyString) {
    msg_type_ = new ::std::string;
  }
  return msg_type_;
}
inline ::std::string* NonRpcMsg::release_msg_type() {
  clear_has_msg_type();
  if (msg_type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_type_;
    msg_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void NonRpcMsg::set_allocated_msg_type(::std::string* msg_type) {
  if (msg_type_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_type_;
  }
  if (msg_type) {
    set_has_msg_type();
    msg_type_ = msg_type;
  } else {
    clear_has_msg_type();
    msg_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required bytes msg_body = 2;
inline bool NonRpcMsg::has_msg_body() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NonRpcMsg::set_has_msg_body() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NonRpcMsg::clear_has_msg_body() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NonRpcMsg::clear_msg_body() {
  if (msg_body_ != &::google::protobuf::internal::kEmptyString) {
    msg_body_->clear();
  }
  clear_has_msg_body();
}
inline const ::std::string& NonRpcMsg::msg_body() const {
  return *msg_body_;
}
inline void NonRpcMsg::set_msg_body(const ::std::string& value) {
  set_has_msg_body();
  if (msg_body_ == &::google::protobuf::internal::kEmptyString) {
    msg_body_ = new ::std::string;
  }
  msg_body_->assign(value);
}
inline void NonRpcMsg::set_msg_body(const char* value) {
  set_has_msg_body();
  if (msg_body_ == &::google::protobuf::internal::kEmptyString) {
    msg_body_ = new ::std::string;
  }
  msg_body_->assign(value);
}
inline void NonRpcMsg::set_msg_body(const void* value, size_t size) {
  set_has_msg_body();
  if (msg_body_ == &::google::protobuf::internal::kEmptyString) {
    msg_body_ = new ::std::string;
  }
  msg_body_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NonRpcMsg::mutable_msg_body() {
  set_has_msg_body();
  if (msg_body_ == &::google::protobuf::internal::kEmptyString) {
    msg_body_ = new ::std::string;
  }
  return msg_body_;
}
inline ::std::string* NonRpcMsg::release_msg_body() {
  clear_has_msg_body();
  if (msg_body_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_body_;
    msg_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void NonRpcMsg::set_allocated_msg_body(::std::string* msg_body) {
  if (msg_body_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_body_;
  }
  if (msg_body) {
    set_has_msg_body();
    msg_body_ = msg_body;
  } else {
    clear_has_msg_body();
    msg_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Box

// optional .thefox.rpc.Call call = 1;
inline bool Box::has_call() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Box::set_has_call() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Box::clear_has_call() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Box::clear_call() {
  if (call_ != NULL) call_->::thefox::rpc::Call::Clear();
  clear_has_call();
}
inline const ::thefox::rpc::Call& Box::call() const {
  return call_ != NULL ? *call_ : *default_instance_->call_;
}
inline ::thefox::rpc::Call* Box::mutable_call() {
  set_has_call();
  if (call_ == NULL) call_ = new ::thefox::rpc::Call;
  return call_;
}
inline ::thefox::rpc::Call* Box::release_call() {
  clear_has_call();
  ::thefox::rpc::Call* temp = call_;
  call_ = NULL;
  return temp;
}
inline void Box::set_allocated_call(::thefox::rpc::Call* call) {
  delete call_;
  call_ = call;
  if (call) {
    set_has_call();
  } else {
    clear_has_call();
  }
}

// optional .thefox.rpc.Reply reply = 2;
inline bool Box::has_reply() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Box::set_has_reply() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Box::clear_has_reply() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Box::clear_reply() {
  if (reply_ != NULL) reply_->::thefox::rpc::Reply::Clear();
  clear_has_reply();
}
inline const ::thefox::rpc::Reply& Box::reply() const {
  return reply_ != NULL ? *reply_ : *default_instance_->reply_;
}
inline ::thefox::rpc::Reply* Box::mutable_reply() {
  set_has_reply();
  if (reply_ == NULL) reply_ = new ::thefox::rpc::Reply;
  return reply_;
}
inline ::thefox::rpc::Reply* Box::release_reply() {
  clear_has_reply();
  ::thefox::rpc::Reply* temp = reply_;
  reply_ = NULL;
  return temp;
}
inline void Box::set_allocated_reply(::thefox::rpc::Reply* reply) {
  delete reply_;
  reply_ = reply;
  if (reply) {
    set_has_reply();
  } else {
    clear_has_reply();
  }
}

// optional .thefox.rpc.NonRpcMsg nonrpc_msg = 3;
inline bool Box::has_nonrpc_msg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Box::set_has_nonrpc_msg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Box::clear_has_nonrpc_msg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Box::clear_nonrpc_msg() {
  if (nonrpc_msg_ != NULL) nonrpc_msg_->::thefox::rpc::NonRpcMsg::Clear();
  clear_has_nonrpc_msg();
}
inline const ::thefox::rpc::NonRpcMsg& Box::nonrpc_msg() const {
  return nonrpc_msg_ != NULL ? *nonrpc_msg_ : *default_instance_->nonrpc_msg_;
}
inline ::thefox::rpc::NonRpcMsg* Box::mutable_nonrpc_msg() {
  set_has_nonrpc_msg();
  if (nonrpc_msg_ == NULL) nonrpc_msg_ = new ::thefox::rpc::NonRpcMsg;
  return nonrpc_msg_;
}
inline ::thefox::rpc::NonRpcMsg* Box::release_nonrpc_msg() {
  clear_has_nonrpc_msg();
  ::thefox::rpc::NonRpcMsg* temp = nonrpc_msg_;
  nonrpc_msg_ = NULL;
  return temp;
}
inline void Box::set_allocated_nonrpc_msg(::thefox::rpc::NonRpcMsg* nonrpc_msg) {
  delete nonrpc_msg_;
  nonrpc_msg_ = nonrpc_msg;
  if (nonrpc_msg) {
    set_has_nonrpc_msg();
  } else {
    clear_has_nonrpc_msg();
  }
}

// -------------------------------------------------------------------

// Placeholder

// -------------------------------------------------------------------

// HeartBeath


// @@protoc_insertion_point(namespace_scope)

}  // namespace rpc
}  // namespace thefox

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rpc_2eproto__INCLUDED
