// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Head.proto

#ifndef PROTOBUF_Head_2eproto__INCLUDED
#define PROTOBUF_Head_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace thefox {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Head_2eproto();
void protobuf_AssignDesc_Head_2eproto();
void protobuf_ShutdownFile_Head_2eproto();

class Head;

// ===================================================================

class Head : public ::google::protobuf::Message {
 public:
  Head();
  virtual ~Head();

  Head(const Head& from);

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Head& default_instance();

  void Swap(Head* other);

  // implements Message ----------------------------------------------

  Head* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sequence = 1;
  inline bool has_sequence() const;
  inline void clear_sequence();
  static const int kSequenceFieldNumber = 1;
  inline ::google::protobuf::int32 sequence() const;
  inline void set_sequence(::google::protobuf::int32 value);

  // required string body_type = 2;
  inline bool has_body_type() const;
  inline void clear_body_type();
  static const int kBodyTypeFieldNumber = 2;
  inline const ::std::string& body_type() const;
  inline void set_body_type(const ::std::string& value);
  inline void set_body_type(const char* value);
  inline void set_body_type(const char* value, size_t size);
  inline ::std::string* mutable_body_type();
  inline ::std::string* release_body_type();
  inline void set_allocated_body_type(::std::string* body_type);

  // @@protoc_insertion_point(class_scope:thefox.Head)
 private:
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_body_type();
  inline void clear_has_body_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* body_type_;
  ::google::protobuf::int32 sequence_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Head_2eproto();
  friend void protobuf_AssignDesc_Head_2eproto();
  friend void protobuf_ShutdownFile_Head_2eproto();

  void InitAsDefaultInstance();
  static Head* default_instance_;
};
// ===================================================================


// ===================================================================

// Head

// required int32 sequence = 1;
inline bool Head::has_sequence() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Head::set_has_sequence() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Head::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Head::clear_sequence() {
  sequence_ = 0;
  clear_has_sequence();
}
inline ::google::protobuf::int32 Head::sequence() const {
  return sequence_;
}
inline void Head::set_sequence(::google::protobuf::int32 value) {
  set_has_sequence();
  sequence_ = value;
}

// required string body_type = 2;
inline bool Head::has_body_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Head::set_has_body_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Head::clear_has_body_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Head::clear_body_type() {
  if (body_type_ != &::google::protobuf::internal::kEmptyString) {
    body_type_->clear();
  }
  clear_has_body_type();
}
inline const ::std::string& Head::body_type() const {
  return *body_type_;
}
inline void Head::set_body_type(const ::std::string& value) {
  set_has_body_type();
  if (body_type_ == &::google::protobuf::internal::kEmptyString) {
    body_type_ = new ::std::string;
  }
  body_type_->assign(value);
}
inline void Head::set_body_type(const char* value) {
  set_has_body_type();
  if (body_type_ == &::google::protobuf::internal::kEmptyString) {
    body_type_ = new ::std::string;
  }
  body_type_->assign(value);
}
inline void Head::set_body_type(const char* value, size_t size) {
  set_has_body_type();
  if (body_type_ == &::google::protobuf::internal::kEmptyString) {
    body_type_ = new ::std::string;
  }
  body_type_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Head::mutable_body_type() {
  set_has_body_type();
  if (body_type_ == &::google::protobuf::internal::kEmptyString) {
    body_type_ = new ::std::string;
  }
  return body_type_;
}
inline ::std::string* Head::release_body_type() {
  clear_has_body_type();
  if (body_type_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = body_type_;
    body_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Head::set_allocated_body_type(::std::string* body_type) {
  if (body_type_ != &::google::protobuf::internal::kEmptyString) {
    delete body_type_;
  }
  if (body_type) {
    set_has_body_type();
    body_type_ = body_type;
  } else {
    clear_has_body_type();
    body_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace thefox

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Head_2eproto__INCLUDED
